[build]
  # Use pnpm for package management
  command = "pnpm build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  # Specify Node.js version
  NODE_VERSION = "20"
  # Enable pnpm
  NPM_FLAGS = "--shamefully-hoist"

# Redirect all API calls to Netlify Functions
[[redirects]]
  from = "/api/uploadthing/*"
  to = "/.netlify/functions/uploadthing/:splat"
  status = 200

# SPA fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
